name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGTALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save impressdemo
      - run: kubectl rollout restart deployment auth-depl
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
